apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: hello
    app.com: raging
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hello
    app.com: raging
